---
permalink: intro-family.html 
keywords: introduction, how astra works, how Astra works, what Astra is, astra control, kubernetes, astra control service, astra control center 
summary: Astra는 상태 저장 애플리케이션의 운영을 단순화하는 Kubernetes 애플리케이션 데이터 라이프사이클 관리 서비스입니다. Kubernetes 워크로드를 손쉽게 보호, 백업, 마이그레이션하고 정상 작동하는 애플리케이션 클론을 즉시 생성할 수 있습니다. 
---
= Astra 제품군에 대해 알아보십시오
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Astra 제품군은 클라우드 네이티브 애플리케이션을 위한 애플리케이션 데이터 관리 및 스토리지를 제공합니다.

Astra 오퍼링은 다음과 같습니다.

* * Astra Control *: 퍼블릭 클라우드와 온프레미스 모두에서 Kubernetes 워크로드를 관리, 보호 및 이동하는 애플리케이션 인식 데이터 관리 툴을 사용합니다
+
** * Astra Control Service *: NetApp에서 관리하는 서비스를 퍼블릭 클라우드의 Kubernetes 워크로드 데이터 관리에 사용합니다.
** * Astra Control Center *: 사내 Kubernetes 워크로드의 데이터 관리에 자가 관리 소프트웨어를 사용합니다.


* * Astra Trident *: NetApp 스토리지 공급자와 함께 CSI(Container Storage Interface)를 준수하는 스토리지 프로비저닝 및 관리 기능을 Kubernetes 워크로드에 사용합니다.




== 아스트라 컨트롤

Astra Control은 Kubernetes 애플리케이션 데이터 라이프사이클 관리 솔루션으로, 상태 저장 애플리케이션의 운영을 단순화합니다. Kubernetes 워크로드를 손쉽게 보호, 백업, 마이그레이션하고 정상 작동하는 애플리케이션 클론을 즉시 생성할 수 있습니다.



=== 피처

Astra Control은 Kubernetes 애플리케이션 데이터 라이프사이클 관리에 중요한 기능을 제공합니다.

* 영구 스토리지를 자동으로 관리합니다
* 애플리케이션 인식 필요 시 스냅샷과 백업을 생성합니다
* 정책 기반 스냅샷 및 백업 작업 자동화
* Kubernetes 클러스터 간에 애플리케이션 및 데이터를 마이그레이션합니다
* 스테이징 환경에서 운영 환경으로 애플리케이션 클론 생성
* 애플리케이션 상태 및 보호 상태를 시각화합니다
* 사용자 인터페이스 또는 API를 사용하여 백업 및 마이그레이션 워크플로우 구현




=== 구축 모델

Astra Control은 두 가지 배포 모델로 제공됩니다.

* * Astra Control Service *: AWS(Amazon Web Services), AKS(Azure Kubernetes Service), GKE(Google Kubernetes Engine)에서 Kubernetes 클러스터의 애플리케이션 인식 데이터 관리를 제공하는 NetApp 관리 서비스입니다.
+
https://docs.netapp.com/us-en/astra/index.html["Astra Control Service 문서"^]

* * Astra Control Center *: 사내 환경에서 실행되는 Kubernetes 클러스터의 애플리케이션 인식 데이터 관리를 제공하는 자체 관리 소프트웨어입니다.
+
https://docs.netapp.com/us-en/astra-control-center/["Astra Control Center 문서"^]



[cols="1h,2a,2a"]
|===
|  | Astra 제어 서비스 | Astra 제어 센터 


| 어떻게 제공됩니까?  a| 
NetApp에서 제공하는 완전 관리형 클라우드 서비스
 a| 
소프트웨어를 다운로드, 설치 및 관리할 수 있습니다



| 어디에 호스팅됩니까?  a| 
NetApp에서 제공하는 다양한 퍼블릭 클라우드 지원
 a| 
에 제공한 Kubernetes 클러스터



| 어떻게 업데이트됩니까?  a| 
NetApp에서 관리합니다
 a| 
모든 업데이트를 관리합니다



| 스토리지 백엔드 지원이란 무엇입니까?  a| 
* Amazon 웹 서비스:
+
** Amazon EBS
** NetApp ONTAP용 Amazon FSx


* Google 클라우드:
+
** Google 영구 디스크
** NetApp Cloud Volumes Service를 참조하십시오


* Microsoft Azure:
+
** Azure 관리 디스크
** Azure NetApp Files



 a| 
* NetApp ONTAP AFF 및 FAS 시스템
* Cloud Volumes ONTAP 스토리지 백엔드


|===


== 아스트라 트리덴트

Astra Trident는 Kubernetes 컨테이너 스토리지 인터페이스(CSI) 드라이버인 NetApp의 오픈 소스 구현입니다. Astra Trident는 Kubernetes 애플리케이션연결을 위한 오케스트레이션 및 데이터 연결을 제공합니다.

https://docs.netapp.com/us-en/trident/index.html["Astra Trident 문서"^]



== 를 참조하십시오

* https://docs.netapp.com/us-en/astra/index.html["Astra Control Service 문서"^]
* https://docs.netapp.com/us-en/astra-control-center/["Astra Control Center 문서"^]
* https://docs.netapp.com/us-en/trident/index.html["Astra Trident 문서"^]
* https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API를 참조하십시오"^]
* https://docs.netapp.com/us-en/cloudinsights/["Cloud Insights 설명서"^]
* https://docs.netapp.com/us-en/ontap/index.html["ONTAP 설명서"^]

